/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	teamv1alpha1 "kubeform.dev/provider-grafana-api/apis/team/v1alpha1"
	versioned "kubeform.dev/provider-grafana-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-grafana-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-grafana-api/client/listers/team/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PreferencesInformer provides access to a shared informer and lister for
// Preferenceses.
type PreferencesInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PreferencesLister
}

type preferencesInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPreferencesInformer constructs a new informer for Preferences type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPreferencesInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPreferencesInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPreferencesInformer constructs a new informer for Preferences type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPreferencesInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TeamV1alpha1().Preferenceses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TeamV1alpha1().Preferenceses(namespace).Watch(context.TODO(), options)
			},
		},
		&teamv1alpha1.Preferences{},
		resyncPeriod,
		indexers,
	)
}

func (f *preferencesInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPreferencesInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *preferencesInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&teamv1alpha1.Preferences{}, f.defaultInformer)
}

func (f *preferencesInformer) Lister() v1alpha1.PreferencesLister {
	return v1alpha1.NewPreferencesLister(f.Informer().GetIndexer())
}
