/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-grafana-api/apis/synthetic/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMonitoringChecks implements MonitoringCheckInterface
type FakeMonitoringChecks struct {
	Fake *FakeSyntheticV1alpha1
	ns   string
}

var monitoringchecksResource = schema.GroupVersionResource{Group: "synthetic.grafana.kubeform.com", Version: "v1alpha1", Resource: "monitoringchecks"}

var monitoringchecksKind = schema.GroupVersionKind{Group: "synthetic.grafana.kubeform.com", Version: "v1alpha1", Kind: "MonitoringCheck"}

// Get takes name of the monitoringCheck, and returns the corresponding monitoringCheck object, and an error if there is any.
func (c *FakeMonitoringChecks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MonitoringCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(monitoringchecksResource, c.ns, name), &v1alpha1.MonitoringCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringCheck), err
}

// List takes label and field selectors, and returns the list of MonitoringChecks that match those selectors.
func (c *FakeMonitoringChecks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MonitoringCheckList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(monitoringchecksResource, monitoringchecksKind, c.ns, opts), &v1alpha1.MonitoringCheckList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MonitoringCheckList{ListMeta: obj.(*v1alpha1.MonitoringCheckList).ListMeta}
	for _, item := range obj.(*v1alpha1.MonitoringCheckList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested monitoringChecks.
func (c *FakeMonitoringChecks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(monitoringchecksResource, c.ns, opts))

}

// Create takes the representation of a monitoringCheck and creates it.  Returns the server's representation of the monitoringCheck, and an error, if there is any.
func (c *FakeMonitoringChecks) Create(ctx context.Context, monitoringCheck *v1alpha1.MonitoringCheck, opts v1.CreateOptions) (result *v1alpha1.MonitoringCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(monitoringchecksResource, c.ns, monitoringCheck), &v1alpha1.MonitoringCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringCheck), err
}

// Update takes the representation of a monitoringCheck and updates it. Returns the server's representation of the monitoringCheck, and an error, if there is any.
func (c *FakeMonitoringChecks) Update(ctx context.Context, monitoringCheck *v1alpha1.MonitoringCheck, opts v1.UpdateOptions) (result *v1alpha1.MonitoringCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(monitoringchecksResource, c.ns, monitoringCheck), &v1alpha1.MonitoringCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringCheck), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMonitoringChecks) UpdateStatus(ctx context.Context, monitoringCheck *v1alpha1.MonitoringCheck, opts v1.UpdateOptions) (*v1alpha1.MonitoringCheck, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(monitoringchecksResource, "status", c.ns, monitoringCheck), &v1alpha1.MonitoringCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringCheck), err
}

// Delete takes name of the monitoringCheck and deletes it. Returns an error if one occurs.
func (c *FakeMonitoringChecks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(monitoringchecksResource, c.ns, name), &v1alpha1.MonitoringCheck{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMonitoringChecks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(monitoringchecksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MonitoringCheckList{})
	return err
}

// Patch applies the patch and returns the patched monitoringCheck.
func (c *FakeMonitoringChecks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MonitoringCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(monitoringchecksResource, c.ns, name, pt, data, subresources...), &v1alpha1.MonitoringCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringCheck), err
}
