/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-grafana-api/apis/data/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSourcePermissions implements SourcePermissionInterface
type FakeSourcePermissions struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var sourcepermissionsResource = schema.GroupVersionResource{Group: "data.grafana.kubeform.com", Version: "v1alpha1", Resource: "sourcepermissions"}

var sourcepermissionsKind = schema.GroupVersionKind{Group: "data.grafana.kubeform.com", Version: "v1alpha1", Kind: "SourcePermission"}

// Get takes name of the sourcePermission, and returns the corresponding sourcePermission object, and an error if there is any.
func (c *FakeSourcePermissions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SourcePermission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sourcepermissionsResource, c.ns, name), &v1alpha1.SourcePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourcePermission), err
}

// List takes label and field selectors, and returns the list of SourcePermissions that match those selectors.
func (c *FakeSourcePermissions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SourcePermissionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sourcepermissionsResource, sourcepermissionsKind, c.ns, opts), &v1alpha1.SourcePermissionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SourcePermissionList{ListMeta: obj.(*v1alpha1.SourcePermissionList).ListMeta}
	for _, item := range obj.(*v1alpha1.SourcePermissionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sourcePermissions.
func (c *FakeSourcePermissions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sourcepermissionsResource, c.ns, opts))

}

// Create takes the representation of a sourcePermission and creates it.  Returns the server's representation of the sourcePermission, and an error, if there is any.
func (c *FakeSourcePermissions) Create(ctx context.Context, sourcePermission *v1alpha1.SourcePermission, opts v1.CreateOptions) (result *v1alpha1.SourcePermission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sourcepermissionsResource, c.ns, sourcePermission), &v1alpha1.SourcePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourcePermission), err
}

// Update takes the representation of a sourcePermission and updates it. Returns the server's representation of the sourcePermission, and an error, if there is any.
func (c *FakeSourcePermissions) Update(ctx context.Context, sourcePermission *v1alpha1.SourcePermission, opts v1.UpdateOptions) (result *v1alpha1.SourcePermission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sourcepermissionsResource, c.ns, sourcePermission), &v1alpha1.SourcePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourcePermission), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSourcePermissions) UpdateStatus(ctx context.Context, sourcePermission *v1alpha1.SourcePermission, opts v1.UpdateOptions) (*v1alpha1.SourcePermission, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sourcepermissionsResource, "status", c.ns, sourcePermission), &v1alpha1.SourcePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourcePermission), err
}

// Delete takes name of the sourcePermission and deletes it. Returns an error if one occurs.
func (c *FakeSourcePermissions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sourcepermissionsResource, c.ns, name), &v1alpha1.SourcePermission{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSourcePermissions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sourcepermissionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SourcePermissionList{})
	return err
}

// Patch applies the patch and returns the patched sourcePermission.
func (c *FakeSourcePermissions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SourcePermission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sourcepermissionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SourcePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourcePermission), err
}
