/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-grafana-api/apis/team/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExternalGroups implements ExternalGroupInterface
type FakeExternalGroups struct {
	Fake *FakeTeamV1alpha1
	ns   string
}

var externalgroupsResource = schema.GroupVersionResource{Group: "team.grafana.kubeform.com", Version: "v1alpha1", Resource: "externalgroups"}

var externalgroupsKind = schema.GroupVersionKind{Group: "team.grafana.kubeform.com", Version: "v1alpha1", Kind: "ExternalGroup"}

// Get takes name of the externalGroup, and returns the corresponding externalGroup object, and an error if there is any.
func (c *FakeExternalGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ExternalGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(externalgroupsResource, c.ns, name), &v1alpha1.ExternalGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalGroup), err
}

// List takes label and field selectors, and returns the list of ExternalGroups that match those selectors.
func (c *FakeExternalGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ExternalGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(externalgroupsResource, externalgroupsKind, c.ns, opts), &v1alpha1.ExternalGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExternalGroupList{ListMeta: obj.(*v1alpha1.ExternalGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExternalGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested externalGroups.
func (c *FakeExternalGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(externalgroupsResource, c.ns, opts))

}

// Create takes the representation of a externalGroup and creates it.  Returns the server's representation of the externalGroup, and an error, if there is any.
func (c *FakeExternalGroups) Create(ctx context.Context, externalGroup *v1alpha1.ExternalGroup, opts v1.CreateOptions) (result *v1alpha1.ExternalGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(externalgroupsResource, c.ns, externalGroup), &v1alpha1.ExternalGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalGroup), err
}

// Update takes the representation of a externalGroup and updates it. Returns the server's representation of the externalGroup, and an error, if there is any.
func (c *FakeExternalGroups) Update(ctx context.Context, externalGroup *v1alpha1.ExternalGroup, opts v1.UpdateOptions) (result *v1alpha1.ExternalGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(externalgroupsResource, c.ns, externalGroup), &v1alpha1.ExternalGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExternalGroups) UpdateStatus(ctx context.Context, externalGroup *v1alpha1.ExternalGroup, opts v1.UpdateOptions) (*v1alpha1.ExternalGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(externalgroupsResource, "status", c.ns, externalGroup), &v1alpha1.ExternalGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalGroup), err
}

// Delete takes name of the externalGroup and deletes it. Returns an error if one occurs.
func (c *FakeExternalGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(externalgroupsResource, c.ns, name), &v1alpha1.ExternalGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExternalGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(externalgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExternalGroupList{})
	return err
}

// Patch applies the patch and returns the patched externalGroup.
func (c *FakeExternalGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ExternalGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(externalgroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ExternalGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalGroup), err
}
