/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	syntheticv1alpha1 "kubeform.dev/provider-grafana-api/apis/synthetic/v1alpha1"
	versioned "kubeform.dev/provider-grafana-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-grafana-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-grafana-api/client/listers/synthetic/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MonitoringProbeInformer provides access to a shared informer and lister for
// MonitoringProbes.
type MonitoringProbeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MonitoringProbeLister
}

type monitoringProbeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMonitoringProbeInformer constructs a new informer for MonitoringProbe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMonitoringProbeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMonitoringProbeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMonitoringProbeInformer constructs a new informer for MonitoringProbe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMonitoringProbeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SyntheticV1alpha1().MonitoringProbes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SyntheticV1alpha1().MonitoringProbes(namespace).Watch(context.TODO(), options)
			},
		},
		&syntheticv1alpha1.MonitoringProbe{},
		resyncPeriod,
		indexers,
	)
}

func (f *monitoringProbeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMonitoringProbeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *monitoringProbeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&syntheticv1alpha1.MonitoringProbe{}, f.defaultInformer)
}

func (f *monitoringProbeInformer) Lister() v1alpha1.MonitoringProbeLister {
	return v1alpha1.NewMonitoringProbeLister(f.Informer().GetIndexer())
}
