apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: grafana.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: stacks.cloud.grafana.kubeform.com
spec:
  group: cloud.grafana.kubeform.com
  names:
    kind: Stack
    listKind: StackList
    plural: stacks
    singular: stack
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  alertmanagerName:
                    description: Name of the Alertmanager instance configured for
                      this stack.
                    type: string
                  alertmanagerStatus:
                    description: Status of the Alertmanager instance configured for
                      this stack.
                    type: string
                  alertmanagerURL:
                    description: Base URL of the Alertmanager instance configured
                      for this stack.
                    type: string
                  alertmanagerUserID:
                    description: User ID of the Alertmanager instance configured for
                      this stack.
                    format: int64
                    type: integer
                  description:
                    description: Description of stack.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name of stack. Conventionally matches the url of
                      the instance (e.g. “<stack_slug>.grafana.net”).
                    type: string
                  orgID:
                    description: Organization id to assign to this stack.
                    format: int64
                    type: integer
                  orgName:
                    description: Organization name to assign to this stack.
                    type: string
                  orgSlug:
                    description: Organization slug to assign to this stack.
                    type: string
                  prometheusName:
                    description: Prometheus name for this instance.
                    type: string
                  prometheusRemoteEndpoint:
                    description: Use this URL to query hosted metrics data e.g. Prometheus
                      data source in Grafana
                    type: string
                  prometheusRemoteWriteEndpoint:
                    description: Use this URL to send prometheus metrics to Grafana
                      cloud
                    type: string
                  prometheusStatus:
                    description: Prometheus status for this instance.
                    type: string
                  prometheusURL:
                    description: Prometheus url for this instance.
                    type: string
                  prometheusUserID:
                    description: Promehteus user ID. Used for e.g. remote_write.
                    format: int64
                    type: integer
                  regionSlug:
                    description: Region slug to assign to this stack. Changing region
                      will destroy the existing stack and create a new one in the
                      desired region
                    type: string
                  slug:
                    description: Subdomain that the Grafana instance will be available
                      at (i.e. setting slug to “<stack_slug>” will make the instance
                      available at “https://<stack_slug>.grafana.net".
                    type: string
                  status:
                    description: Status of the stack.
                    type: string
                  url:
                    description: Custom URL for the Grafana instance. Must have a
                      CNAME setup to point to `.grafana.net` before creating the stack
                    type: string
                required:
                - name
                - slug
                type: object
              state:
                properties:
                  alertmanagerName:
                    description: Name of the Alertmanager instance configured for
                      this stack.
                    type: string
                  alertmanagerStatus:
                    description: Status of the Alertmanager instance configured for
                      this stack.
                    type: string
                  alertmanagerURL:
                    description: Base URL of the Alertmanager instance configured
                      for this stack.
                    type: string
                  alertmanagerUserID:
                    description: User ID of the Alertmanager instance configured for
                      this stack.
                    format: int64
                    type: integer
                  description:
                    description: Description of stack.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name of stack. Conventionally matches the url of
                      the instance (e.g. “<stack_slug>.grafana.net”).
                    type: string
                  orgID:
                    description: Organization id to assign to this stack.
                    format: int64
                    type: integer
                  orgName:
                    description: Organization name to assign to this stack.
                    type: string
                  orgSlug:
                    description: Organization slug to assign to this stack.
                    type: string
                  prometheusName:
                    description: Prometheus name for this instance.
                    type: string
                  prometheusRemoteEndpoint:
                    description: Use this URL to query hosted metrics data e.g. Prometheus
                      data source in Grafana
                    type: string
                  prometheusRemoteWriteEndpoint:
                    description: Use this URL to send prometheus metrics to Grafana
                      cloud
                    type: string
                  prometheusStatus:
                    description: Prometheus status for this instance.
                    type: string
                  prometheusURL:
                    description: Prometheus url for this instance.
                    type: string
                  prometheusUserID:
                    description: Promehteus user ID. Used for e.g. remote_write.
                    format: int64
                    type: integer
                  regionSlug:
                    description: Region slug to assign to this stack. Changing region
                      will destroy the existing stack and create a new one in the
                      desired region
                    type: string
                  slug:
                    description: Subdomain that the Grafana instance will be available
                      at (i.e. setting slug to “<stack_slug>” will make the instance
                      available at “https://<stack_slug>.grafana.net".
                    type: string
                  status:
                    description: Status of the stack.
                    type: string
                  url:
                    description: Custom URL for the Grafana instance. Must have a
                      CNAME setup to point to `.grafana.net` before creating the stack
                    type: string
                required:
                - name
                - slug
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
