apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: grafana.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: panels.library.grafana.kubeform.com
spec:
  group: library.grafana.kubeform.com
  names:
    kind: Panel
    listKind: PanelList
    plural: panels
    singular: panel
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  created:
                    description: Timestamp when the library panel was created.
                    type: string
                  dashboardIDS:
                    description: Numerical IDs of Grafana dashboards containing the
                      library panel.
                    items:
                      format: int64
                      type: integer
                    type: array
                  description:
                    description: Description of the library panel.
                    type: string
                  folderID:
                    description: ID of the folder where the library panel is stored.
                    format: int64
                    type: integer
                  folderName:
                    description: Name of the folder containing the library panel.
                    type: string
                  folderUid:
                    description: Unique ID (UID) of the folder containing the library
                      panel.
                    type: string
                  id:
                    type: string
                  modelJSON:
                    description: The JSON model for the library panel.
                    type: string
                  name:
                    description: Name of the library panel.
                    type: string
                  orgID:
                    description: The numeric ID of the library panel computed by Grafana.
                    format: int64
                    type: integer
                  panelID:
                    description: The numeric ID of the library panel computed by Grafana.
                    format: int64
                    type: integer
                  type:
                    description: Type of the library panel (eg. text).
                    type: string
                  uid:
                    description: The unique identifier (UID) of a library panel uniquely
                      identifies library panels between multiple Grafana installs.
                      It’s automatically generated unless you specify it during library
                      panel creation.The UID provides consistent URLs for accessing
                      library panels and when syncing library panels between multiple
                      Grafana installs.
                    type: string
                  updated:
                    description: Timestamp when the library panel was last modified.
                    type: string
                  version:
                    description: Version of the library panel.
                    format: int64
                    type: integer
                required:
                - modelJSON
                - name
                type: object
              state:
                properties:
                  created:
                    description: Timestamp when the library panel was created.
                    type: string
                  dashboardIDS:
                    description: Numerical IDs of Grafana dashboards containing the
                      library panel.
                    items:
                      format: int64
                      type: integer
                    type: array
                  description:
                    description: Description of the library panel.
                    type: string
                  folderID:
                    description: ID of the folder where the library panel is stored.
                    format: int64
                    type: integer
                  folderName:
                    description: Name of the folder containing the library panel.
                    type: string
                  folderUid:
                    description: Unique ID (UID) of the folder containing the library
                      panel.
                    type: string
                  id:
                    type: string
                  modelJSON:
                    description: The JSON model for the library panel.
                    type: string
                  name:
                    description: Name of the library panel.
                    type: string
                  orgID:
                    description: The numeric ID of the library panel computed by Grafana.
                    format: int64
                    type: integer
                  panelID:
                    description: The numeric ID of the library panel computed by Grafana.
                    format: int64
                    type: integer
                  type:
                    description: Type of the library panel (eg. text).
                    type: string
                  uid:
                    description: The unique identifier (UID) of a library panel uniquely
                      identifies library panels between multiple Grafana installs.
                      It’s automatically generated unless you specify it during library
                      panel creation.The UID provides consistent URLs for accessing
                      library panels and when syncing library panels between multiple
                      Grafana installs.
                    type: string
                  updated:
                    description: Timestamp when the library panel was last modified.
                    type: string
                  version:
                    description: Version of the library panel.
                    format: int64
                    type: integer
                required:
                - modelJSON
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
